= Rebecca Oei - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Eggventory

---

== Overview

Eggventory (Engineering Got General Inventory) is an inventory management system that is specially designed to be used by lab technicians in Engineering labs. It was created to facilitate the tracking of movement of inventory in an Engineering
laboratory in an easy-to-use interface. Eggventory interprets user commands through a CLI with predictive search, and displays the inventory components in a GUI. 

== Summary of contributions

* *Feature*: added *???*
** What it does: 
** Justification: 
** Highlights: 
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: 

* *Shared Code Contributions*
** Logic (Parser) module: Developed main Parser structure. Wrote Parser code for ParseAdd and ParseDelete. 
** Loan Feature: Created the base code for Loan feature, including Loan and LoanList classes. 

* *Code contributed*: https://nuscs2113-ay1920s1.github.io/dashboard/#search=cyanoei[Reposense] [https://github.com[Test code]] _Note: Contribution graph was affected by a rebase, but contributions are still properly attributed._

* *Other contributions*:

** Project management:
*** As team leader of Eggventory - in charge of keeping track of the project progress, managing issues and PRs for milestones. 
** Enhancements to existing features:
*** 
*** 
** Documentation:
*** Was responsible for final editing and submission of Week 7 and Week 10 drafts of User Guide and Developer guide.
** Community:
*** PRs reviewed (with non-trivial review comments): 
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/217[#217] 
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/220[#220]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/223[#223]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/251[#251]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/261[#261]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/269[#269]
*** Bugs fixed for team code: 
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/210[#210]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/236[#236]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/240[#240]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
