= Rebecca Oei - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Eggventory

---

== Overview

Eggventory (Engineering Got General Inventory) is an inventory management system that is specially designed to be used by lab technicians in Engineering labs. It was created to facilitate the tracking of movement of inventory in an Engineering
laboratory in an easy-to-use interface. Eggventory interprets user commands through a CLI with predictive search, and displays the inventory components in a GUI. 

== Summary of contributions

* *Feature: Minimum required quantity*
** What it does: Allows users to set a minimum required quantity of a stock. This the minimum amount of a particular stock that the inventory has to have on hand at any given time. After loans or lost items are recorded, Eggventory will warn users if the stock quantity has fallen below the minimum. Users can also request a list of stocks that are present in less than the minimum required quantity.

** Justification: Eggventory inherently can notify users when a stock has completely run out, but it is not reasonable to wait until the stock is completely depleted. Realistically, users would prefer to have some notice beforehand, to have time to order new stocks or track down overdue loans. This feature also allows the minimum value to be user-defined, depending the importance of the stock within the inventory.   

** Highlights: This feature requires careful integration with the "edit minimum", "loan" and "lost" functions. There are thus three different scenarios (detailed in the Developer Guide below) where checks have to be performed. 


* *Shared Code Contributions*
** Logic (Parser) module: Developed main Parser structure. Wrote logic for ParseAdd and ParseDelete. (Code: 
https://github.com/AY1920S1-CS2113T-F09-3/main/blob/master/src/main/java/eggventory/logic/parsers/Parser.java[Parser.java],
https://github.com/AY1920S1-CS2113T-F09-3/main/blob/master/src/main/java/eggventory/logic/parsers/ParseAdd.java[ParseAdd.java],
https://github.com/AY1920S1-CS2113T-F09-3/main/blob/master/src/main/java/eggventory/logic/parsers/ParseDelete.java[ParseDelete.java])

** Loan Feature: Created the base code for Loan feature. (Code: 
https://github.com/AY1920S1-CS2113T-F09-3/main/blob/master/src/main/java/eggventory/model/loans/Loan.java[Loan.java],
https://github.com/AY1920S1-CS2113T-F09-3/main/blob/master/src/main/java/eggventory/model/loans/LoanPair.java[LoanPair.java],
https://github.com/AY1920S1-CS2113T-F09-3/main/blob/master/src/main/java/eggventory/model/LoanList.java[LoanList.java])

** UniqueStock extension: Created base code for UniqueStock extention (has since been pushed back to v2.0). (Code:
https://github.com/AY1920S1-CS2113T-F09-3/main/blob/master/src/main/java/eggventory/model/items/UniqueStock.java[UniqueStock.java],
https://github.com/AY1920S1-CS2113T-F09-3/main/blob/master/src/main/java/eggventory/model/items/Item.java[Item.java])

* *Code contributed*: https://nuscs2113-ay1920s1.github.io/dashboard/#search=cyanoei[Reposense] _(Note: Contribution graph was affected by a rebase, but contributions are still properly attributed.)_

* *Other contributions*:

** Project management:
*** As team leader of Eggventory - in charge of keeping track of the project progress, managing issues and PRs for milestones. 

** Documentation:
*** Was responsible for final editing and submission of Week 7 and Week 10 drafts of User Guide and Developer guide.

** Community:
*** PRs reviewed: 
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/217[#217] 
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/220[#220]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/223[#223]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/251[#251]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/261[#261]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/269[#269]
*** Bugs fixed for team code: 
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/210[#210]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/236[#236]
https://github.com/AY1920S1-CS2113T-F09-3/main/pull/240[#240]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]

